version: '3.3'
services:
  app:
      build:
        context: ../../
        dockerfile: docker/Dockerfile
      ports:
        - "5001:5000"
      image: mysqlbigquery
      container_name: "mysqlbigqueryinstall"
      command: ["python","/src/install.py"]