version: '3.3'
services:
  app:
      build:
        context: ../../
        dockerfile: docker/Dockerfile
      ports:
        - "5002:5000"
      image: mysqlbigquery
      container_name: "mysqlbigqueryproduce"
      command: ["python","/src/produce.py"]