version: '3.3'
services:
  app:
      build:
        context: ../../
        dockerfile: docker/Dockerfile
      ports:
        - "5000:5000"
      image: mysqlbigquery
      container_name: "mysqlbigqueryconsume"
      command: ["python","/src/consume.py"]